// ============================================================================
//
// Copyright (c) 2006-2015, Talend Inc.
//
// This source code has been automatically generated by_Talend Open Studio for Data Integration
// / Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


package bi_forest.carga_dim_clientes_0_1;

import routines.Numeric;
import routines.DataOperation;
import routines.TalendDataGenerator;
import routines.TalendStringUtil;
import routines.TalendString;
import routines.StringHandling;
import routines.Relational;
import routines.TalendDate;
import routines.Mathematical;
import routines.system.*;
import routines.system.api.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.math.BigDecimal;
import java.io.ByteArrayOutputStream;
import java.io.ByteArrayInputStream;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.ObjectOutputStream;
import java.io.ObjectInputStream;
import java.io.IOException;
import java.util.Comparator;
 





@SuppressWarnings("unused")

/**
 * Job: CARGA_DIM_CLIENTES Purpose: <br>
 * Description: CADASTRO DE CLIENTES <br>
 * @author user@talend.com
 * @version 7.3.1.20200219_1130
 * @status 
 */
public class CARGA_DIM_CLIENTES implements TalendJob {

protected static void logIgnoredError(String message, Throwable cause) {
       System.err.println(message);
       if (cause != null) {
               cause.printStackTrace();
       }

}


	public final Object obj = new Object();

	// for transmiting parameters purpose
	private Object valueObject = null;

	public Object getValueObject() {
		return this.valueObject;
	}

	public void setValueObject(Object valueObject) {
		this.valueObject = valueObject;
	}
	
	private final static String defaultCharset = java.nio.charset.Charset.defaultCharset().name();

	
	private final static String utf8Charset = "UTF-8";
	//contains type for every context property
	public class PropertiesWithType extends java.util.Properties {
		private static final long serialVersionUID = 1L;
		private java.util.Map<String,String> propertyTypes = new java.util.HashMap<>();
		
		public PropertiesWithType(java.util.Properties properties){
			super(properties);
		}
		public PropertiesWithType(){
			super();
		}
		
		public void setContextType(String key, String type) {
			propertyTypes.put(key,type);
		}
	
		public String getContextType(String key) {
			return propertyTypes.get(key);
		}
	}
	
	// create and load default properties
	private java.util.Properties defaultProps = new java.util.Properties();
	// create application properties with default
	public class ContextProperties extends PropertiesWithType {

		private static final long serialVersionUID = 1L;

		public ContextProperties(java.util.Properties properties){
			super(properties);
		}
		public ContextProperties(){
			super();
		}

		public void synchronizeContext(){
			
		}

	}
	protected ContextProperties context = new ContextProperties(); // will be instanciated by MS.
	public ContextProperties getContext() {
		return this.context;
	}
	private final String jobVersion = "0.1";
	private final String jobName = "CARGA_DIM_CLIENTES";
	private final String projectName = "BI_FOREST";
	public Integer errorCode = null;
	private String currentComponent = "";
	
		private final java.util.Map<String, Object> globalMap = new java.util.HashMap<String, Object>();
        private final static java.util.Map<String, Object> junitGlobalMap = new java.util.HashMap<String, Object>();
	
		private final java.util.Map<String, Long> start_Hash = new java.util.HashMap<String, Long>();
		private final java.util.Map<String, Long> end_Hash = new java.util.HashMap<String, Long>();
		private final java.util.Map<String, Boolean> ok_Hash = new java.util.HashMap<String, Boolean>();
		public  final java.util.List<String[]> globalBuffer = new java.util.ArrayList<String[]>();
	

private RunStat runStat = new RunStat();

	// OSGi DataSource
	private final static String KEY_DB_DATASOURCES = "KEY_DB_DATASOURCES";
	
	private final static String KEY_DB_DATASOURCES_RAW = "KEY_DB_DATASOURCES_RAW";

	public void setDataSources(java.util.Map<String, javax.sql.DataSource> dataSources) {
		java.util.Map<String, routines.system.TalendDataSource> talendDataSources = new java.util.HashMap<String, routines.system.TalendDataSource>();
		for (java.util.Map.Entry<String, javax.sql.DataSource> dataSourceEntry : dataSources.entrySet()) {
			talendDataSources.put(dataSourceEntry.getKey(), new routines.system.TalendDataSource(dataSourceEntry.getValue()));
		}
		globalMap.put(KEY_DB_DATASOURCES, talendDataSources);
		globalMap.put(KEY_DB_DATASOURCES_RAW, new java.util.HashMap<String, javax.sql.DataSource>(dataSources));
	}


private final java.io.ByteArrayOutputStream baos = new java.io.ByteArrayOutputStream();
private final java.io.PrintStream errorMessagePS = new java.io.PrintStream(new java.io.BufferedOutputStream(baos));

public String getExceptionStackTrace() {
	if ("failure".equals(this.getStatus())) {
		errorMessagePS.flush();
		return baos.toString();
	}
	return null;
}

private Exception exception;

public Exception getException() {
	if ("failure".equals(this.getStatus())) {
		return this.exception;
	}
	return null;
}

private class TalendException extends Exception {

	private static final long serialVersionUID = 1L;

	private java.util.Map<String, Object> globalMap = null;
	private Exception e = null;
	private String currentComponent = null;
	private String virtualComponentName = null;
	
	public void setVirtualComponentName (String virtualComponentName){
		this.virtualComponentName = virtualComponentName;
	}

	private TalendException(Exception e, String errorComponent, final java.util.Map<String, Object> globalMap) {
		this.currentComponent= errorComponent;
		this.globalMap = globalMap;
		this.e = e;
	}

	public Exception getException() {
		return this.e;
	}

	public String getCurrentComponent() {
		return this.currentComponent;
	}

	
    public String getExceptionCauseMessage(Exception e){
        Throwable cause = e;
        String message = null;
        int i = 10;
        while (null != cause && 0 < i--) {
            message = cause.getMessage();
            if (null == message) {
                cause = cause.getCause();
            } else {
                break;          
            }
        }
        if (null == message) {
            message = e.getClass().getName();
        }   
        return message;
    }

	@Override
	public void printStackTrace() {
		if (!(e instanceof TalendException || e instanceof TDieException)) {
			if(virtualComponentName!=null && currentComponent.indexOf(virtualComponentName+"_")==0){
				globalMap.put(virtualComponentName+"_ERROR_MESSAGE",getExceptionCauseMessage(e));
			}
			globalMap.put(currentComponent+"_ERROR_MESSAGE",getExceptionCauseMessage(e));
			System.err.println("Exception in component " + currentComponent + " (" + jobName + ")");
		}
		if (!(e instanceof TDieException)) {
			if(e instanceof TalendException){
				e.printStackTrace();
			} else {
				e.printStackTrace();
				e.printStackTrace(errorMessagePS);
				CARGA_DIM_CLIENTES.this.exception = e;
			}
		}
		if (!(e instanceof TalendException)) {
		try {
			for (java.lang.reflect.Method m : this.getClass().getEnclosingClass().getMethods()) {
				if (m.getName().compareTo(currentComponent + "_error") == 0) {
					m.invoke(CARGA_DIM_CLIENTES.this, new Object[] { e , currentComponent, globalMap});
					break;
				}
			}

			if(!(e instanceof TDieException)){
			}
		} catch (Exception e) {
			this.e.printStackTrace();
		}
		}
	}
}

			public void tDBInput_1_error(Exception exception, String errorComponent, final java.util.Map<String, Object> globalMap) throws TalendException {
				
				end_Hash.put(errorComponent, System.currentTimeMillis());
				
				status = "failure";
				
					tDBInput_1_onSubJobError(exception, errorComponent, globalMap);
			}
			
			public void tMap_1_error(Exception exception, String errorComponent, final java.util.Map<String, Object> globalMap) throws TalendException {
				
				end_Hash.put(errorComponent, System.currentTimeMillis());
				
				status = "failure";
				
					tDBInput_1_onSubJobError(exception, errorComponent, globalMap);
			}
			
			public void tDBSCD_1_error(Exception exception, String errorComponent, final java.util.Map<String, Object> globalMap) throws TalendException {
				
				end_Hash.put(errorComponent, System.currentTimeMillis());
				
				status = "failure";
				
					tDBInput_1_onSubJobError(exception, errorComponent, globalMap);
			}
			
			public void tDBInput_1_onSubJobError(Exception exception, String errorComponent, final java.util.Map<String, Object> globalMap) throws TalendException {

resumeUtil.addLog("SYSTEM_LOG", "NODE:"+ errorComponent, "", Thread.currentThread().getId()+ "", "FATAL", "", exception.getMessage(), ResumeUtil.getExceptionStackTrace(exception),"");

			}
	






public static class SAIDAStruct implements routines.system.IPersistableRow<SAIDAStruct> {
    final static byte[] commonByteArrayLock_BI_FOREST_CARGA_DIM_CLIENTES = new byte[0];
    static byte[] commonByteArray_BI_FOREST_CARGA_DIM_CLIENTES = new byte[0];
	protected static final int DEFAULT_HASHCODE = 1;
    protected static final int PRIME = 31;
    protected int hashCode = DEFAULT_HASHCODE;
    public boolean hashCodeDirty = true;

    public String loopKey;



	
			    public int SK_CLIENTE;

				public int getSK_CLIENTE () {
					return this.SK_CLIENTE;
				}
				
			    public int COD_EMPRESA;

				public int getCOD_EMPRESA () {
					return this.COD_EMPRESA;
				}
				
			    public int ID_CLIENTE;

				public int getID_CLIENTE () {
					return this.ID_CLIENTE;
				}
				
			    public String RAZAO_CLIENTE;

				public String getRAZAO_CLIENTE () {
					return this.RAZAO_CLIENTE;
				}
				
			    public String FANTASIA;

				public String getFANTASIA () {
					return this.FANTASIA;
				}
				
			    public String ENDERECO;

				public String getENDERECO () {
					return this.ENDERECO;
				}
				
			    public String NRO;

				public String getNRO () {
					return this.NRO;
				}
				
			    public String BAIRRO;

				public String getBAIRRO () {
					return this.BAIRRO;
				}
				
			    public String COD_CIDADE;

				public String getCOD_CIDADE () {
					return this.COD_CIDADE;
				}
				
			    public String CEP;

				public String getCEP () {
					return this.CEP;
				}
				
			    public String CNPJ_CPF;

				public String getCNPJ_CPF () {
					return this.CNPJ_CPF;
				}
				
			    public String TIPO_CLIENTE;

				public String getTIPO_CLIENTE () {
					return this.TIPO_CLIENTE;
				}
				
			    public java.util.Date DATA_CADASTRO;

				public java.util.Date getDATA_CADASTRO () {
					return this.DATA_CADASTRO;
				}
				
			    public String SITUACAO;

				public String getSITUACAO () {
					return this.SITUACAO;
				}
				


	@Override
	public int hashCode() {
		if (this.hashCodeDirty) {
			final int prime = PRIME;
			int result = DEFAULT_HASHCODE;
	
							result = prime * result + (int) this.SK_CLIENTE;
						
    		this.hashCode = result;
    		this.hashCodeDirty = false;
		}
		return this.hashCode;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) return true;
		if (obj == null) return false;
		if (getClass() != obj.getClass()) return false;
		final SAIDAStruct other = (SAIDAStruct) obj;
		
						if (this.SK_CLIENTE != other.SK_CLIENTE)
							return false;
					

		return true;
    }

	public void copyDataTo(SAIDAStruct other) {

		other.SK_CLIENTE = this.SK_CLIENTE;
	            other.COD_EMPRESA = this.COD_EMPRESA;
	            other.ID_CLIENTE = this.ID_CLIENTE;
	            other.RAZAO_CLIENTE = this.RAZAO_CLIENTE;
	            other.FANTASIA = this.FANTASIA;
	            other.ENDERECO = this.ENDERECO;
	            other.NRO = this.NRO;
	            other.BAIRRO = this.BAIRRO;
	            other.COD_CIDADE = this.COD_CIDADE;
	            other.CEP = this.CEP;
	            other.CNPJ_CPF = this.CNPJ_CPF;
	            other.TIPO_CLIENTE = this.TIPO_CLIENTE;
	            other.DATA_CADASTRO = this.DATA_CADASTRO;
	            other.SITUACAO = this.SITUACAO;
	            
	}

	public void copyKeysDataTo(SAIDAStruct other) {

		other.SK_CLIENTE = this.SK_CLIENTE;
	            	
	}




	private String readString(ObjectInputStream dis) throws IOException{
		String strReturn = null;
		int length = 0;
        length = dis.readInt();
		if (length == -1) {
			strReturn = null;
		} else {
			if(length > commonByteArray_BI_FOREST_CARGA_DIM_CLIENTES.length) {
				if(length < 1024 && commonByteArray_BI_FOREST_CARGA_DIM_CLIENTES.length == 0) {
   					commonByteArray_BI_FOREST_CARGA_DIM_CLIENTES = new byte[1024];
				} else {
   					commonByteArray_BI_FOREST_CARGA_DIM_CLIENTES = new byte[2 * length];
   				}
			}
			dis.readFully(commonByteArray_BI_FOREST_CARGA_DIM_CLIENTES, 0, length);
			strReturn = new String(commonByteArray_BI_FOREST_CARGA_DIM_CLIENTES, 0, length, utf8Charset);
		}
		return strReturn;
	}

    private void writeString(String str, ObjectOutputStream dos) throws IOException{
		if(str == null) {
            dos.writeInt(-1);
		} else {
            byte[] byteArray = str.getBytes(utf8Charset);
	    	dos.writeInt(byteArray.length);
			dos.write(byteArray);
    	}
    }

	private java.util.Date readDate(ObjectInputStream dis) throws IOException{
		java.util.Date dateReturn = null;
        int length = 0;
        length = dis.readByte();
		if (length == -1) {
			dateReturn = null;
		} else {
	    	dateReturn = new Date(dis.readLong());
		}
		return dateReturn;
	}

    private void writeDate(java.util.Date date1, ObjectOutputStream dos) throws IOException{
		if(date1 == null) {
            dos.writeByte(-1);
		} else {
			dos.writeByte(0);
	    	dos.writeLong(date1.getTime());
    	}
    }

    public void readData(ObjectInputStream dis) {

		synchronized(commonByteArrayLock_BI_FOREST_CARGA_DIM_CLIENTES) {

        	try {

        		int length = 0;
		
			        this.SK_CLIENTE = dis.readInt();
					
			        this.COD_EMPRESA = dis.readInt();
					
			        this.ID_CLIENTE = dis.readInt();
					
					this.RAZAO_CLIENTE = readString(dis);
					
					this.FANTASIA = readString(dis);
					
					this.ENDERECO = readString(dis);
					
					this.NRO = readString(dis);
					
					this.BAIRRO = readString(dis);
					
					this.COD_CIDADE = readString(dis);
					
					this.CEP = readString(dis);
					
					this.CNPJ_CPF = readString(dis);
					
					this.TIPO_CLIENTE = readString(dis);
					
					this.DATA_CADASTRO = readDate(dis);
					
					this.SITUACAO = readString(dis);
					
        	} catch (IOException e) {
	            throw new RuntimeException(e);

		

        }

		

      }


    }

    public void writeData(ObjectOutputStream dos) {
        try {

		
					// int
				
		            	dos.writeInt(this.SK_CLIENTE);
					
					// int
				
		            	dos.writeInt(this.COD_EMPRESA);
					
					// int
				
		            	dos.writeInt(this.ID_CLIENTE);
					
					// String
				
						writeString(this.RAZAO_CLIENTE,dos);
					
					// String
				
						writeString(this.FANTASIA,dos);
					
					// String
				
						writeString(this.ENDERECO,dos);
					
					// String
				
						writeString(this.NRO,dos);
					
					// String
				
						writeString(this.BAIRRO,dos);
					
					// String
				
						writeString(this.COD_CIDADE,dos);
					
					// String
				
						writeString(this.CEP,dos);
					
					// String
				
						writeString(this.CNPJ_CPF,dos);
					
					// String
				
						writeString(this.TIPO_CLIENTE,dos);
					
					// java.util.Date
				
						writeDate(this.DATA_CADASTRO,dos);
					
					// String
				
						writeString(this.SITUACAO,dos);
					
        	} catch (IOException e) {
	            throw new RuntimeException(e);
        }


    }


    public String toString() {

		StringBuilder sb = new StringBuilder();
		sb.append(super.toString());
		sb.append("[");
		sb.append("SK_CLIENTE="+String.valueOf(SK_CLIENTE));
		sb.append(",COD_EMPRESA="+String.valueOf(COD_EMPRESA));
		sb.append(",ID_CLIENTE="+String.valueOf(ID_CLIENTE));
		sb.append(",RAZAO_CLIENTE="+RAZAO_CLIENTE);
		sb.append(",FANTASIA="+FANTASIA);
		sb.append(",ENDERECO="+ENDERECO);
		sb.append(",NRO="+NRO);
		sb.append(",BAIRRO="+BAIRRO);
		sb.append(",COD_CIDADE="+COD_CIDADE);
		sb.append(",CEP="+CEP);
		sb.append(",CNPJ_CPF="+CNPJ_CPF);
		sb.append(",TIPO_CLIENTE="+TIPO_CLIENTE);
		sb.append(",DATA_CADASTRO="+String.valueOf(DATA_CADASTRO));
		sb.append(",SITUACAO="+SITUACAO);
	    sb.append("]");

	    return sb.toString();
    }

    /**
     * Compare keys
     */
    public int compareTo(SAIDAStruct other) {

		int returnValue = -1;
		
						returnValue = checkNullsAndCompare(this.SK_CLIENTE, other.SK_CLIENTE);
						if(returnValue != 0) {
							return returnValue;
						}

					
	    return returnValue;
    }


    private int checkNullsAndCompare(Object object1, Object object2) {
        int returnValue = 0;
		if (object1 instanceof Comparable && object2 instanceof Comparable) {
            returnValue = ((Comparable) object1).compareTo(object2);
        } else if (object1 != null && object2 != null) {
            returnValue = compareStrings(object1.toString(), object2.toString());
        } else if (object1 == null && object2 != null) {
            returnValue = 1;
        } else if (object1 != null && object2 == null) {
            returnValue = -1;
        } else {
            returnValue = 0;
        }

        return returnValue;
    }

    private int compareStrings(String string1, String string2) {
        return string1.compareTo(string2);
    }


}

public static class row1Struct implements routines.system.IPersistableRow<row1Struct> {
    final static byte[] commonByteArrayLock_BI_FOREST_CARGA_DIM_CLIENTES = new byte[0];
    static byte[] commonByteArray_BI_FOREST_CARGA_DIM_CLIENTES = new byte[0];

	
			    public int COD_EMPRESA;

				public int getCOD_EMPRESA () {
					return this.COD_EMPRESA;
				}
				
			    public int ID_CLIENTE;

				public int getID_CLIENTE () {
					return this.ID_CLIENTE;
				}
				
			    public String RAZAO_CLIENTE;

				public String getRAZAO_CLIENTE () {
					return this.RAZAO_CLIENTE;
				}
				
			    public String FANTASIA;

				public String getFANTASIA () {
					return this.FANTASIA;
				}
				
			    public String ENDERECO;

				public String getENDERECO () {
					return this.ENDERECO;
				}
				
			    public String NRO;

				public String getNRO () {
					return this.NRO;
				}
				
			    public String BAIRRO;

				public String getBAIRRO () {
					return this.BAIRRO;
				}
				
			    public String COD_CIDADE;

				public String getCOD_CIDADE () {
					return this.COD_CIDADE;
				}
				
			    public String CEP;

				public String getCEP () {
					return this.CEP;
				}
				
			    public String CNPJ_CPF;

				public String getCNPJ_CPF () {
					return this.CNPJ_CPF;
				}
				
			    public String TIPO_CLIENTE;

				public String getTIPO_CLIENTE () {
					return this.TIPO_CLIENTE;
				}
				
			    public java.util.Date DATA_CADASTRO;

				public java.util.Date getDATA_CADASTRO () {
					return this.DATA_CADASTRO;
				}
				
			    public Integer COD_PAGTO;

				public Integer getCOD_PAGTO () {
					return this.COD_PAGTO;
				}
				
			    public String SITUACAO;

				public String getSITUACAO () {
					return this.SITUACAO;
				}
				



	private String readString(ObjectInputStream dis) throws IOException{
		String strReturn = null;
		int length = 0;
        length = dis.readInt();
		if (length == -1) {
			strReturn = null;
		} else {
			if(length > commonByteArray_BI_FOREST_CARGA_DIM_CLIENTES.length) {
				if(length < 1024 && commonByteArray_BI_FOREST_CARGA_DIM_CLIENTES.length == 0) {
   					commonByteArray_BI_FOREST_CARGA_DIM_CLIENTES = new byte[1024];
				} else {
   					commonByteArray_BI_FOREST_CARGA_DIM_CLIENTES = new byte[2 * length];
   				}
			}
			dis.readFully(commonByteArray_BI_FOREST_CARGA_DIM_CLIENTES, 0, length);
			strReturn = new String(commonByteArray_BI_FOREST_CARGA_DIM_CLIENTES, 0, length, utf8Charset);
		}
		return strReturn;
	}

    private void writeString(String str, ObjectOutputStream dos) throws IOException{
		if(str == null) {
            dos.writeInt(-1);
		} else {
            byte[] byteArray = str.getBytes(utf8Charset);
	    	dos.writeInt(byteArray.length);
			dos.write(byteArray);
    	}
    }

	private java.util.Date readDate(ObjectInputStream dis) throws IOException{
		java.util.Date dateReturn = null;
        int length = 0;
        length = dis.readByte();
		if (length == -1) {
			dateReturn = null;
		} else {
	    	dateReturn = new Date(dis.readLong());
		}
		return dateReturn;
	}

    private void writeDate(java.util.Date date1, ObjectOutputStream dos) throws IOException{
		if(date1 == null) {
            dos.writeByte(-1);
		} else {
			dos.writeByte(0);
	    	dos.writeLong(date1.getTime());
    	}
    }
	private Integer readInteger(ObjectInputStream dis) throws IOException{
		Integer intReturn;
        int length = 0;
        length = dis.readByte();
		if (length == -1) {
			intReturn = null;
		} else {
	    	intReturn = dis.readInt();
		}
		return intReturn;
	}

	private void writeInteger(Integer intNum, ObjectOutputStream dos) throws IOException{
		if(intNum == null) {
            dos.writeByte(-1);
		} else {
			dos.writeByte(0);
	    	dos.writeInt(intNum);
    	}
	}

    public void readData(ObjectInputStream dis) {

		synchronized(commonByteArrayLock_BI_FOREST_CARGA_DIM_CLIENTES) {

        	try {

        		int length = 0;
		
			        this.COD_EMPRESA = dis.readInt();
					
			        this.ID_CLIENTE = dis.readInt();
					
					this.RAZAO_CLIENTE = readString(dis);
					
					this.FANTASIA = readString(dis);
					
					this.ENDERECO = readString(dis);
					
					this.NRO = readString(dis);
					
					this.BAIRRO = readString(dis);
					
					this.COD_CIDADE = readString(dis);
					
					this.CEP = readString(dis);
					
					this.CNPJ_CPF = readString(dis);
					
					this.TIPO_CLIENTE = readString(dis);
					
					this.DATA_CADASTRO = readDate(dis);
					
						this.COD_PAGTO = readInteger(dis);
					
					this.SITUACAO = readString(dis);
					
        	} catch (IOException e) {
	            throw new RuntimeException(e);

		

        }

		

      }


    }

    public void writeData(ObjectOutputStream dos) {
        try {

		
					// int
				
		            	dos.writeInt(this.COD_EMPRESA);
					
					// int
				
		            	dos.writeInt(this.ID_CLIENTE);
					
					// String
				
						writeString(this.RAZAO_CLIENTE,dos);
					
					// String
				
						writeString(this.FANTASIA,dos);
					
					// String
				
						writeString(this.ENDERECO,dos);
					
					// String
				
						writeString(this.NRO,dos);
					
					// String
				
						writeString(this.BAIRRO,dos);
					
					// String
				
						writeString(this.COD_CIDADE,dos);
					
					// String
				
						writeString(this.CEP,dos);
					
					// String
				
						writeString(this.CNPJ_CPF,dos);
					
					// String
				
						writeString(this.TIPO_CLIENTE,dos);
					
					// java.util.Date
				
						writeDate(this.DATA_CADASTRO,dos);
					
					// Integer
				
						writeInteger(this.COD_PAGTO,dos);
					
					// String
				
						writeString(this.SITUACAO,dos);
					
        	} catch (IOException e) {
	            throw new RuntimeException(e);
        }


    }


    public String toString() {

		StringBuilder sb = new StringBuilder();
		sb.append(super.toString());
		sb.append("[");
		sb.append("COD_EMPRESA="+String.valueOf(COD_EMPRESA));
		sb.append(",ID_CLIENTE="+String.valueOf(ID_CLIENTE));
		sb.append(",RAZAO_CLIENTE="+RAZAO_CLIENTE);
		sb.append(",FANTASIA="+FANTASIA);
		sb.append(",ENDERECO="+ENDERECO);
		sb.append(",NRO="+NRO);
		sb.append(",BAIRRO="+BAIRRO);
		sb.append(",COD_CIDADE="+COD_CIDADE);
		sb.append(",CEP="+CEP);
		sb.append(",CNPJ_CPF="+CNPJ_CPF);
		sb.append(",TIPO_CLIENTE="+TIPO_CLIENTE);
		sb.append(",DATA_CADASTRO="+String.valueOf(DATA_CADASTRO));
		sb.append(",COD_PAGTO="+String.valueOf(COD_PAGTO));
		sb.append(",SITUACAO="+SITUACAO);
	    sb.append("]");

	    return sb.toString();
    }

    /**
     * Compare keys
     */
    public int compareTo(row1Struct other) {

		int returnValue = -1;
		
	    return returnValue;
    }


    private int checkNullsAndCompare(Object object1, Object object2) {
        int returnValue = 0;
		if (object1 instanceof Comparable && object2 instanceof Comparable) {
            returnValue = ((Comparable) object1).compareTo(object2);
        } else if (object1 != null && object2 != null) {
            returnValue = compareStrings(object1.toString(), object2.toString());
        } else if (object1 == null && object2 != null) {
            returnValue = 1;
        } else if (object1 != null && object2 == null) {
            returnValue = -1;
        } else {
            returnValue = 0;
        }

        return returnValue;
    }

    private int compareStrings(String string1, String string2) {
        return string1.compareTo(string2);
    }


}
public void tDBInput_1Process(final java.util.Map<String, Object> globalMap) throws TalendException {
	globalMap.put("tDBInput_1_SUBPROCESS_STATE", 0);

 final boolean execStat = this.execStat;
	
		String iterateId = "";
	
	
	String currentComponent = "";
	java.util.Map<String, Object> resourceMap = new java.util.HashMap<String, Object>();

	try {
			// TDI-39566 avoid throwing an useless Exception
			boolean resumeIt = true;
			if (globalResumeTicket == false && resumeEntryMethodName != null) {
				String currentMethodName = new java.lang.Exception().getStackTrace()[0].getMethodName();
				resumeIt = resumeEntryMethodName.equals(currentMethodName);
			}
			if (resumeIt || globalResumeTicket) { //start the resume
				globalResumeTicket = true;



		row1Struct row1 = new row1Struct();
SAIDAStruct SAIDA = new SAIDAStruct();





	
	/**
	 * [tDBSCD_1 begin ] start
	 */

	

	
		
		ok_Hash.put("tDBSCD_1", false);
		start_Hash.put("tDBSCD_1", System.currentTimeMillis());
		
	
	currentComponent="tDBSCD_1";

	
					if(execStat) {
						runStat.updateStatOnConnection(resourceMap,iterateId,0,0,"SAIDA");
					}
				
		int tos_count_tDBSCD_1 = 0;
		



        class SCDSK_tDBSCD_1 {
private int hashCode;
public boolean hashCodeDirty = true;
int ID_CLIENTE;
int COD_EMPRESA;
public boolean equals(Object obj) {
if (this == obj) return true;
if (obj == null) return false;
if (getClass() != obj.getClass()) return false;
final SCDSK_tDBSCD_1 other = (SCDSK_tDBSCD_1) obj;
if (this.ID_CLIENTE!= other.ID_CLIENTE)
return false;

if (this.COD_EMPRESA!= other.COD_EMPRESA)
return false;

return true;
}
public int hashCode() {
if(hashCodeDirty) {
int prime = 31;hashCode = prime * hashCode + ID_CLIENTE;
hashCode = prime * hashCode + COD_EMPRESA;
hashCodeDirty = false;
}
return hashCode;
}
}

    class SCDStruct_tDBSCD_1 {
private String BAIRRO;
private String CEP;
private String CNPJ_CPF;
private String COD_CIDADE;
private java.util.Date DATA_CADASTRO;
private String ENDERECO;
private String FANTASIA;
private String NRO;
private String RAZAO_CLIENTE;
private String SITUACAO;
private String TIPO_CLIENTE;
}

    int nb_line_update_tDBSCD_1 = 0;
    int nb_line_inserted_tDBSCD_1 = 0;
    int nb_line_rejected_tDBSCD_1 = 0;
    String tableName_tDBSCD_1 = null;
	String dbschema_tDBSCD_1 = null;
java.sql.Connection conn_tDBSCD_1 = null;
String dbUser_tDBSCD_1 = null;
    dbschema_tDBSCD_1 = "dbo";
    String driverClass_tDBSCD_1 = "net.sourceforge.jtds.jdbc.Driver";
	
    java.lang.Class.forName(driverClass_tDBSCD_1);
    String port_tDBSCD_1 = "1433";
    String dbname_tDBSCD_1 = "DW" ;
    String url_tDBSCD_1 = "jdbc:jtds:sqlserver://" + "DESKTOP-SKA0L5T" ; 
    if (!"".equals(port_tDBSCD_1)) {
    	url_tDBSCD_1 += ":" + "1433";
    }
    if (!"".equals(dbname_tDBSCD_1)) {
				url_tDBSCD_1 += "//" + "DW"; 
	
    }
    url_tDBSCD_1 += ";appName=" + projectName + ";" + "INSTANCE=OLAP";
    dbUser_tDBSCD_1 = "ETLBI";

 
	final String decryptedPassword_tDBSCD_1 = routines.system.PasswordEncryptUtil.decryptPassword("enc:routine.encryption.key.v1:kWrSW0JPyZ5AbaqzHYweLC3cVXYYJl6JPXGd0CISJsAfs3H/");

    String dbPwd_tDBSCD_1 = decryptedPassword_tDBSCD_1;	
    conn_tDBSCD_1 = java.sql.DriverManager.getConnection(url_tDBSCD_1,dbUser_tDBSCD_1,dbPwd_tDBSCD_1);
	

    if(dbschema_tDBSCD_1 == null || dbschema_tDBSCD_1.trim().length() == 0) {
        tableName_tDBSCD_1 = "DIM_CLIENTES";
    } else {
        tableName_tDBSCD_1 = dbschema_tDBSCD_1 + "].[" + "DIM_CLIENTES";
    }
	org.talend.designer.components.util.mssql.MSSqlGenerateTimestampUtil mssqlGTU_tDBSCD_1 = org.talend.designer.components.util.mssql.MSSqlUtilFactory.getMSSqlGenerateTimestampUtil();	
    String tmpValue_tDBSCD_1 = null;    
        String search_tDBSCD_1 = "SELECT [ID_CLIENTE], [COD_EMPRESA], [BAIRRO], [CEP], [CNPJ_CPF], [COD_CIDADE], [DATA_CADASTRO], [ENDERECO], [FANTASIA], [NRO], [RAZAO_CLIENTE], [SITUACAO], [TIPO_CLIENTE] FROM [" + tableName_tDBSCD_1 + "]";
        java.sql.Statement statement_tDBSCD_1 = conn_tDBSCD_1.createStatement();
        java.sql.ResultSet resultSet_tDBSCD_1 = statement_tDBSCD_1.executeQuery(search_tDBSCD_1);
        java.util.Map<SCDSK_tDBSCD_1, SCDStruct_tDBSCD_1> cache_tDBSCD_1 = new java.util.HashMap<SCDSK_tDBSCD_1, SCDStruct_tDBSCD_1>();
        while(resultSet_tDBSCD_1.next()) {
            SCDSK_tDBSCD_1 sk_tDBSCD_1 = new SCDSK_tDBSCD_1();
            SCDStruct_tDBSCD_1 row_tDBSCD_1 = new SCDStruct_tDBSCD_1();
                    if(resultSet_tDBSCD_1.getObject(1) != null) {
                        sk_tDBSCD_1.ID_CLIENTE = resultSet_tDBSCD_1.getInt(1);
                    }
                    if(resultSet_tDBSCD_1.getObject(2) != null) {
                        sk_tDBSCD_1.COD_EMPRESA = resultSet_tDBSCD_1.getInt(2);
                    }
                    if(resultSet_tDBSCD_1.getObject(3) != null) {
                        row_tDBSCD_1.BAIRRO = resultSet_tDBSCD_1.getString(3);
                    }
                    if(resultSet_tDBSCD_1.getObject(4) != null) {
                        row_tDBSCD_1.CEP = resultSet_tDBSCD_1.getString(4);
                    }
                    if(resultSet_tDBSCD_1.getObject(5) != null) {
                        row_tDBSCD_1.CNPJ_CPF = resultSet_tDBSCD_1.getString(5);
                    }
                    if(resultSet_tDBSCD_1.getObject(6) != null) {
                        row_tDBSCD_1.COD_CIDADE = resultSet_tDBSCD_1.getString(6);
                    }
                     row_tDBSCD_1.DATA_CADASTRO = mssqlGTU_tDBSCD_1.getDate(resultSet_tDBSCD_1.getMetaData(), resultSet_tDBSCD_1, 7);
                    if(resultSet_tDBSCD_1.getObject(8) != null) {
                        row_tDBSCD_1.ENDERECO = resultSet_tDBSCD_1.getString(8);
                    }
                    if(resultSet_tDBSCD_1.getObject(9) != null) {
                        row_tDBSCD_1.FANTASIA = resultSet_tDBSCD_1.getString(9);
                    }
                    if(resultSet_tDBSCD_1.getObject(10) != null) {
                        row_tDBSCD_1.NRO = resultSet_tDBSCD_1.getString(10);
                    }
                    if(resultSet_tDBSCD_1.getObject(11) != null) {
                        row_tDBSCD_1.RAZAO_CLIENTE = resultSet_tDBSCD_1.getString(11);
                    }
                    if(resultSet_tDBSCD_1.getObject(12) != null) {
                        row_tDBSCD_1.SITUACAO = resultSet_tDBSCD_1.getString(12);
                    }
                    if(resultSet_tDBSCD_1.getObject(13) != null) {
                        row_tDBSCD_1.TIPO_CLIENTE = resultSet_tDBSCD_1.getString(13);
                    }
            cache_tDBSCD_1.put(sk_tDBSCD_1, row_tDBSCD_1);
        }
        resultSet_tDBSCD_1.close();
        statement_tDBSCD_1.close();
        int nextSurrogateKey_tDBSCD_1 = 1;
            if(cache_tDBSCD_1.size() > 0) {
        String tmpQuery_tDBSCD_1 = "SELECT MAX([SK_CLIENTE]) FROM [" + tableName_tDBSCD_1 + "]";
        java.sql.Statement tmpStmt_tDBSCD_1 = conn_tDBSCD_1.createStatement();
        java.sql.ResultSet tmpRS_tDBSCD_1 = tmpStmt_tDBSCD_1.executeQuery(tmpQuery_tDBSCD_1);
        if(tmpRS_tDBSCD_1.next() && tmpRS_tDBSCD_1.getObject(1) != null) {
            nextSurrogateKey_tDBSCD_1 = tmpRS_tDBSCD_1.getInt(1) + 1;
        }
        tmpRS_tDBSCD_1.close();
        tmpStmt_tDBSCD_1.close();
            }            
    String insertionSQL_tDBSCD_1 = "INSERT INTO [" + tableName_tDBSCD_1 + "]([SK_CLIENTE], [ID_CLIENTE], [COD_EMPRESA], [BAIRRO], [CEP], [CNPJ_CPF], [COD_CIDADE], [DATA_CADASTRO], [ENDERECO], [FANTASIA], [NRO], [RAZAO_CLIENTE], [SITUACAO], [TIPO_CLIENTE]) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
    java.sql.PreparedStatement insertionStatement_tDBSCD_1 = conn_tDBSCD_1.prepareStatement(insertionSQL_tDBSCD_1);
        String updateSQLForType1_tDBSCD_1 = "UPDATE [" + tableName_tDBSCD_1 + "] SET [BAIRRO] = ?, [CEP] = ?, [CNPJ_CPF] = ?, [COD_CIDADE] = ?, [DATA_CADASTRO] = ?, [ENDERECO] = ?, [FANTASIA] = ?, [NRO] = ?, [RAZAO_CLIENTE] = ?, [SITUACAO] = ?, [TIPO_CLIENTE] = ? WHERE [ID_CLIENTE] = ? AND [COD_EMPRESA] = ?";
        java.sql.PreparedStatement updateForType1_tDBSCD_1 = conn_tDBSCD_1.prepareStatement(updateSQLForType1_tDBSCD_1);        
    
        SCDSK_tDBSCD_1 lookUpKey_tDBSCD_1 = null;        
    SCDStruct_tDBSCD_1 lookUpValue_tDBSCD_1 = null;

 



/**
 * [tDBSCD_1 begin ] stop
 */



	
	/**
	 * [tMap_1 begin ] start
	 */

	

	
		
		ok_Hash.put("tMap_1", false);
		start_Hash.put("tMap_1", System.currentTimeMillis());
		
	
	currentComponent="tMap_1";

	
					if(execStat) {
						runStat.updateStatOnConnection(resourceMap,iterateId,0,0,"row1");
					}
				
		int tos_count_tMap_1 = 0;
		




// ###############################
// # Lookup's keys initialization
// ###############################        

// ###############################
// # Vars initialization
class  Var__tMap_1__Struct  {
}
Var__tMap_1__Struct Var__tMap_1 = new Var__tMap_1__Struct();
// ###############################

// ###############################
// # Outputs initialization
SAIDAStruct SAIDA_tmp = new SAIDAStruct();
// ###############################

        
        



        









 



/**
 * [tMap_1 begin ] stop
 */



	
	/**
	 * [tDBInput_1 begin ] start
	 */

	

	
		
		ok_Hash.put("tDBInput_1", false);
		start_Hash.put("tDBInput_1", System.currentTimeMillis());
		
	
	currentComponent="tDBInput_1";

	
		int tos_count_tDBInput_1 = 0;
		
	
    
	
			org.talend.designer.components.util.mssql.MSSqlGenerateTimestampUtil mssqlGTU_tDBInput_1 = org.talend.designer.components.util.mssql.MSSqlUtilFactory.getMSSqlGenerateTimestampUtil();
			
			java.util.List<String> talendToDBList_tDBInput_1 = new java.util.ArrayList();
			String[] talendToDBArray_tDBInput_1  = new String[]{"FLOAT","NUMERIC","NUMERIC IDENTITY","DECIMAL","DECIMAL IDENTITY","REAL"}; 
			java.util.Collections.addAll(talendToDBList_tDBInput_1, talendToDBArray_tDBInput_1); 
		    int nb_line_tDBInput_1 = 0;
		    java.sql.Connection conn_tDBInput_1 = null;
				String driverClass_tDBInput_1 = "net.sourceforge.jtds.jdbc.Driver";
			    java.lang.Class jdbcclazz_tDBInput_1 = java.lang.Class.forName(driverClass_tDBInput_1);
				String dbUser_tDBInput_1 = "ETLBI";
				
				 
	final String decryptedPassword_tDBInput_1 = routines.system.PasswordEncryptUtil.decryptPassword("enc:routine.encryption.key.v1:eTYklNNucMccS82VLQkmys6Rz4GBTThvQB5f7x+4J4aCJW8N");
				
				String dbPwd_tDBInput_1 = decryptedPassword_tDBInput_1;
				
		    String port_tDBInput_1 = "1433";
		    String dbname_tDBInput_1 = "DW" ;
			String url_tDBInput_1 = "jdbc:jtds:sqlserver://" + "DESKTOP-SKA0L5T" ;
		    if (!"".equals(port_tDBInput_1)) {
		    	url_tDBInput_1 += ":" + "1433";
		    }
		    if (!"".equals(dbname_tDBInput_1)) {
				url_tDBInput_1 += "//" + "DW"; 
		    }
		    url_tDBInput_1 += ";appName=" + projectName + ";" + "INSTANCE=OLAP";
		    String dbschema_tDBInput_1 = "dbo";
				
				conn_tDBInput_1 = java.sql.DriverManager.getConnection(url_tDBInput_1,dbUser_tDBInput_1,dbPwd_tDBInput_1);
		        
		    
			java.sql.Statement stmt_tDBInput_1 = conn_tDBInput_1.createStatement();

		    String dbquery_tDBInput_1 = "SELECT dbo.STG_CLIENTES.COD_EMPRESA,\n		dbo.STG_CLIENTES.ID_CLIENTE,\n		dbo.STG_CLIENTES.RAZAO_CLIENTE,\n		dbo.STG_CLIENTE"
+"S.FANTASIA,\n		dbo.STG_CLIENTES.ENDERECO,\n		dbo.STG_CLIENTES.NRO,\n		dbo.STG_CLIENTES.BAIRRO,\n		dbo.STG_CLIENTES.COD_CIDAD"
+"E,\n		dbo.STG_CLIENTES.CEP,\n		dbo.STG_CLIENTES.CNPJ_CPF,\n		dbo.STG_CLIENTES.TIPO_CLIENTE,\n		dbo.STG_CLIENTES.DATA_CADASTR"
+"O,\n		dbo.STG_CLIENTES.COD_PAGTO,\n		dbo.STG_CLIENTES.SITUACAO\nFROM	dbo.STG_CLIENTES";
			

            	globalMap.put("tDBInput_1_QUERY",dbquery_tDBInput_1);
		    java.sql.ResultSet rs_tDBInput_1 = null;

		    try {
		    	rs_tDBInput_1 = stmt_tDBInput_1.executeQuery(dbquery_tDBInput_1);
		    	java.sql.ResultSetMetaData rsmd_tDBInput_1 = rs_tDBInput_1.getMetaData();
		    	int colQtyInRs_tDBInput_1 = rsmd_tDBInput_1.getColumnCount();

		    String tmpContent_tDBInput_1 = null;
		    
		    
		    while (rs_tDBInput_1.next()) {
		        nb_line_tDBInput_1++;
		        
							if(colQtyInRs_tDBInput_1 < 1) {
								row1.COD_EMPRESA = 0;
							} else {
		                          
            row1.COD_EMPRESA = rs_tDBInput_1.getInt(1);
            if(rs_tDBInput_1.wasNull()){
                    throw new RuntimeException("Null value in non-Nullable column");
            }
		                    }
							if(colQtyInRs_tDBInput_1 < 2) {
								row1.ID_CLIENTE = 0;
							} else {
		                          
            row1.ID_CLIENTE = rs_tDBInput_1.getInt(2);
            if(rs_tDBInput_1.wasNull()){
                    throw new RuntimeException("Null value in non-Nullable column");
            }
		                    }
							if(colQtyInRs_tDBInput_1 < 3) {
								row1.RAZAO_CLIENTE = null;
							} else {
	                         		
           		tmpContent_tDBInput_1 = rs_tDBInput_1.getString(3);
            if(tmpContent_tDBInput_1 != null) {
            	if (talendToDBList_tDBInput_1 .contains(rsmd_tDBInput_1.getColumnTypeName(3).toUpperCase(java.util.Locale.ENGLISH))) {
            		row1.RAZAO_CLIENTE = FormatterUtils.formatUnwithE(tmpContent_tDBInput_1);
            	} else {
                	row1.RAZAO_CLIENTE = tmpContent_tDBInput_1;
                }
            } else {
                row1.RAZAO_CLIENTE = null;
            }
		                    }
							if(colQtyInRs_tDBInput_1 < 4) {
								row1.FANTASIA = null;
							} else {
	                         		
           		tmpContent_tDBInput_1 = rs_tDBInput_1.getString(4);
            if(tmpContent_tDBInput_1 != null) {
            	if (talendToDBList_tDBInput_1 .contains(rsmd_tDBInput_1.getColumnTypeName(4).toUpperCase(java.util.Locale.ENGLISH))) {
            		row1.FANTASIA = FormatterUtils.formatUnwithE(tmpContent_tDBInput_1);
            	} else {
                	row1.FANTASIA = tmpContent_tDBInput_1;
                }
            } else {
                row1.FANTASIA = null;
            }
		                    }
							if(colQtyInRs_tDBInput_1 < 5) {
								row1.ENDERECO = null;
							} else {
	                         		
           		tmpContent_tDBInput_1 = rs_tDBInput_1.getString(5);
            if(tmpContent_tDBInput_1 != null) {
            	if (talendToDBList_tDBInput_1 .contains(rsmd_tDBInput_1.getColumnTypeName(5).toUpperCase(java.util.Locale.ENGLISH))) {
            		row1.ENDERECO = FormatterUtils.formatUnwithE(tmpContent_tDBInput_1);
            	} else {
                	row1.ENDERECO = tmpContent_tDBInput_1;
                }
            } else {
                row1.ENDERECO = null;
            }
		                    }
							if(colQtyInRs_tDBInput_1 < 6) {
								row1.NRO = null;
							} else {
	                         		
           		tmpContent_tDBInput_1 = rs_tDBInput_1.getString(6);
            if(tmpContent_tDBInput_1 != null) {
            	if (talendToDBList_tDBInput_1 .contains(rsmd_tDBInput_1.getColumnTypeName(6).toUpperCase(java.util.Locale.ENGLISH))) {
            		row1.NRO = FormatterUtils.formatUnwithE(tmpContent_tDBInput_1);
            	} else {
                	row1.NRO = tmpContent_tDBInput_1;
                }
            } else {
                row1.NRO = null;
            }
		                    }
							if(colQtyInRs_tDBInput_1 < 7) {
								row1.BAIRRO = null;
							} else {
	                         		
           		tmpContent_tDBInput_1 = rs_tDBInput_1.getString(7);
            if(tmpContent_tDBInput_1 != null) {
            	if (talendToDBList_tDBInput_1 .contains(rsmd_tDBInput_1.getColumnTypeName(7).toUpperCase(java.util.Locale.ENGLISH))) {
            		row1.BAIRRO = FormatterUtils.formatUnwithE(tmpContent_tDBInput_1);
            	} else {
                	row1.BAIRRO = tmpContent_tDBInput_1;
                }
            } else {
                row1.BAIRRO = null;
            }
		                    }
							if(colQtyInRs_tDBInput_1 < 8) {
								row1.COD_CIDADE = null;
							} else {
	                         		
           		tmpContent_tDBInput_1 = rs_tDBInput_1.getString(8);
            if(tmpContent_tDBInput_1 != null) {
            	if (talendToDBList_tDBInput_1 .contains(rsmd_tDBInput_1.getColumnTypeName(8).toUpperCase(java.util.Locale.ENGLISH))) {
            		row1.COD_CIDADE = FormatterUtils.formatUnwithE(tmpContent_tDBInput_1);
            	} else {
                	row1.COD_CIDADE = tmpContent_tDBInput_1;
                }
            } else {
                row1.COD_CIDADE = null;
            }
		                    }
							if(colQtyInRs_tDBInput_1 < 9) {
								row1.CEP = null;
							} else {
	                         		
           		tmpContent_tDBInput_1 = rs_tDBInput_1.getString(9);
            if(tmpContent_tDBInput_1 != null) {
            	if (talendToDBList_tDBInput_1 .contains(rsmd_tDBInput_1.getColumnTypeName(9).toUpperCase(java.util.Locale.ENGLISH))) {
            		row1.CEP = FormatterUtils.formatUnwithE(tmpContent_tDBInput_1);
            	} else {
                	row1.CEP = tmpContent_tDBInput_1;
                }
            } else {
                row1.CEP = null;
            }
		                    }
							if(colQtyInRs_tDBInput_1 < 10) {
								row1.CNPJ_CPF = null;
							} else {
	                         		
           		tmpContent_tDBInput_1 = rs_tDBInput_1.getString(10);
            if(tmpContent_tDBInput_1 != null) {
            	if (talendToDBList_tDBInput_1 .contains(rsmd_tDBInput_1.getColumnTypeName(10).toUpperCase(java.util.Locale.ENGLISH))) {
            		row1.CNPJ_CPF = FormatterUtils.formatUnwithE(tmpContent_tDBInput_1);
            	} else {
                	row1.CNPJ_CPF = tmpContent_tDBInput_1;
                }
            } else {
                row1.CNPJ_CPF = null;
            }
		                    }
							if(colQtyInRs_tDBInput_1 < 11) {
								row1.TIPO_CLIENTE = null;
							} else {
	                         		
           		tmpContent_tDBInput_1 = rs_tDBInput_1.getString(11);
            if(tmpContent_tDBInput_1 != null) {
            	if (talendToDBList_tDBInput_1 .contains(rsmd_tDBInput_1.getColumnTypeName(11).toUpperCase(java.util.Locale.ENGLISH))) {
            		row1.TIPO_CLIENTE = FormatterUtils.formatUnwithE(tmpContent_tDBInput_1);
            	} else {
                	row1.TIPO_CLIENTE = tmpContent_tDBInput_1;
                }
            } else {
                row1.TIPO_CLIENTE = null;
            }
		                    }
							if(colQtyInRs_tDBInput_1 < 12) {
								row1.DATA_CADASTRO = null;
							} else {
										
			row1.DATA_CADASTRO = mssqlGTU_tDBInput_1.getDate(rsmd_tDBInput_1, rs_tDBInput_1, 12);
			
		                    }
							if(colQtyInRs_tDBInput_1 < 13) {
								row1.COD_PAGTO = null;
							} else {
		                          
            row1.COD_PAGTO = rs_tDBInput_1.getInt(13);
            if(rs_tDBInput_1.wasNull()){
                    row1.COD_PAGTO = null;
            }
		                    }
							if(colQtyInRs_tDBInput_1 < 14) {
								row1.SITUACAO = null;
							} else {
	                         		
           		tmpContent_tDBInput_1 = rs_tDBInput_1.getString(14);
            if(tmpContent_tDBInput_1 != null) {
            	if (talendToDBList_tDBInput_1 .contains(rsmd_tDBInput_1.getColumnTypeName(14).toUpperCase(java.util.Locale.ENGLISH))) {
            		row1.SITUACAO = FormatterUtils.formatUnwithE(tmpContent_tDBInput_1);
            	} else {
                	row1.SITUACAO = tmpContent_tDBInput_1;
                }
            } else {
                row1.SITUACAO = null;
            }
		                    }
					





 



/**
 * [tDBInput_1 begin ] stop
 */
	
	/**
	 * [tDBInput_1 main ] start
	 */

	

	
	
	currentComponent="tDBInput_1";

	

 


	tos_count_tDBInput_1++;

/**
 * [tDBInput_1 main ] stop
 */
	
	/**
	 * [tDBInput_1 process_data_begin ] start
	 */

	

	
	
	currentComponent="tDBInput_1";

	

 



/**
 * [tDBInput_1 process_data_begin ] stop
 */

	
	/**
	 * [tMap_1 main ] start
	 */

	

	
	
	currentComponent="tMap_1";

	
					if(execStat){
						runStat.updateStatOnConnection(iterateId,1,1,"row1");
					}
					

		
		
		boolean hasCasePrimitiveKeyWithNull_tMap_1 = false;
		
        // ###############################
        // # Input tables (lookups)
		  boolean rejectedInnerJoin_tMap_1 = false;
		  boolean mainRowRejected_tMap_1 = false;
            				    								  
		// ###############################
        { // start of Var scope
        
	        // ###############################
        	// # Vars tables
        
Var__tMap_1__Struct Var = Var__tMap_1;// ###############################
        // ###############################
        // # Output tables

SAIDA = null;


// # Output table : 'SAIDA'
SAIDA_tmp.SK_CLIENTE = 0;
SAIDA_tmp.COD_EMPRESA = row1.COD_EMPRESA ;
SAIDA_tmp.ID_CLIENTE = row1.ID_CLIENTE ;
SAIDA_tmp.RAZAO_CLIENTE = row1.RAZAO_CLIENTE ;
SAIDA_tmp.FANTASIA = row1.FANTASIA ;
SAIDA_tmp.ENDERECO = row1.ENDERECO ;
SAIDA_tmp.NRO = row1.NRO ;
SAIDA_tmp.BAIRRO = row1.BAIRRO ;
SAIDA_tmp.COD_CIDADE = row1.COD_CIDADE ;
SAIDA_tmp.CEP = row1.CEP ;
SAIDA_tmp.CNPJ_CPF = row1.CNPJ_CPF ;
SAIDA_tmp.TIPO_CLIENTE = row1.TIPO_CLIENTE ;
SAIDA_tmp.DATA_CADASTRO = row1.DATA_CADASTRO ;
SAIDA_tmp.SITUACAO = row1.SITUACAO ;
SAIDA = SAIDA_tmp;
// ###############################

} // end of Var scope

rejectedInnerJoin_tMap_1 = false;










 


	tos_count_tMap_1++;

/**
 * [tMap_1 main ] stop
 */
	
	/**
	 * [tMap_1 process_data_begin ] start
	 */

	

	
	
	currentComponent="tMap_1";

	

 



/**
 * [tMap_1 process_data_begin ] stop
 */
// Start of branch "SAIDA"
if(SAIDA != null) { 



	
	/**
	 * [tDBSCD_1 main ] start
	 */

	

	
	
	currentComponent="tDBSCD_1";

	
					if(execStat){
						runStat.updateStatOnConnection(iterateId,1,1,"SAIDA");
					}
					

	try {
        lookUpKey_tDBSCD_1 = new SCDSK_tDBSCD_1();
            lookUpKey_tDBSCD_1.ID_CLIENTE = SAIDA.ID_CLIENTE;
            lookUpKey_tDBSCD_1.COD_EMPRESA = SAIDA.COD_EMPRESA;
        lookUpKey_tDBSCD_1.hashCodeDirty = true;
        lookUpValue_tDBSCD_1 = cache_tDBSCD_1.get(lookUpKey_tDBSCD_1);    
    if(lookUpValue_tDBSCD_1 == null) {
            lookUpValue_tDBSCD_1 = new SCDStruct_tDBSCD_1();
                            
                    insertionStatement_tDBSCD_1.setInt(1, nextSurrogateKey_tDBSCD_1);

                    nextSurrogateKey_tDBSCD_1++;
                    insertionStatement_tDBSCD_1.setInt(2, SAIDA.ID_CLIENTE);

                    insertionStatement_tDBSCD_1.setInt(3, SAIDA.COD_EMPRESA);

                    if(SAIDA.BAIRRO == null) {
insertionStatement_tDBSCD_1.setNull(4, java.sql.Types.VARCHAR);
} else {
insertionStatement_tDBSCD_1.setString(4, SAIDA.BAIRRO);
}

                    if(SAIDA.CEP == null) {
insertionStatement_tDBSCD_1.setNull(5, java.sql.Types.VARCHAR);
} else {
insertionStatement_tDBSCD_1.setString(5, SAIDA.CEP);
}

                    if(SAIDA.CNPJ_CPF == null) {
insertionStatement_tDBSCD_1.setNull(6, java.sql.Types.VARCHAR);
} else {
insertionStatement_tDBSCD_1.setString(6, SAIDA.CNPJ_CPF);
}

                    if(SAIDA.COD_CIDADE == null) {
insertionStatement_tDBSCD_1.setNull(7, java.sql.Types.VARCHAR);
} else {
insertionStatement_tDBSCD_1.setString(7, SAIDA.COD_CIDADE);
}

                    if(SAIDA.DATA_CADASTRO == null) {
insertionStatement_tDBSCD_1.setNull(8, java.sql.Types.DATE);
} else {
if(SAIDA.DATA_CADASTRO != null) {
insertionStatement_tDBSCD_1.setTimestamp(8, new java.sql.Timestamp(SAIDA.DATA_CADASTRO.getTime()));
} else {
insertionStatement_tDBSCD_1.setNull(8, java.sql.Types.DATE);
}
}

                    if(SAIDA.ENDERECO == null) {
insertionStatement_tDBSCD_1.setNull(9, java.sql.Types.VARCHAR);
} else {
insertionStatement_tDBSCD_1.setString(9, SAIDA.ENDERECO);
}

                    if(SAIDA.FANTASIA == null) {
insertionStatement_tDBSCD_1.setNull(10, java.sql.Types.VARCHAR);
} else {
insertionStatement_tDBSCD_1.setString(10, SAIDA.FANTASIA);
}

                    if(SAIDA.NRO == null) {
insertionStatement_tDBSCD_1.setNull(11, java.sql.Types.VARCHAR);
} else {
insertionStatement_tDBSCD_1.setString(11, SAIDA.NRO);
}

                    if(SAIDA.RAZAO_CLIENTE == null) {
insertionStatement_tDBSCD_1.setNull(12, java.sql.Types.VARCHAR);
} else {
insertionStatement_tDBSCD_1.setString(12, SAIDA.RAZAO_CLIENTE);
}

                    if(SAIDA.SITUACAO == null) {
insertionStatement_tDBSCD_1.setNull(13, java.sql.Types.VARCHAR);
} else {
insertionStatement_tDBSCD_1.setString(13, SAIDA.SITUACAO);
}

                    if(SAIDA.TIPO_CLIENTE == null) {
insertionStatement_tDBSCD_1.setNull(14, java.sql.Types.VARCHAR);
} else {
insertionStatement_tDBSCD_1.setString(14, SAIDA.TIPO_CLIENTE);
}

        nb_line_inserted_tDBSCD_1 += insertionStatement_tDBSCD_1.executeUpdate();
    } else {
            if((lookUpValue_tDBSCD_1.BAIRRO == null && SAIDA.BAIRRO!= null) || (lookUpValue_tDBSCD_1.BAIRRO != null && !lookUpValue_tDBSCD_1.BAIRRO.equals(SAIDA.BAIRRO)) || (lookUpValue_tDBSCD_1.CEP == null && SAIDA.CEP!= null) || (lookUpValue_tDBSCD_1.CEP != null && !lookUpValue_tDBSCD_1.CEP.equals(SAIDA.CEP)) || (lookUpValue_tDBSCD_1.CNPJ_CPF == null && SAIDA.CNPJ_CPF!= null) || (lookUpValue_tDBSCD_1.CNPJ_CPF != null && !lookUpValue_tDBSCD_1.CNPJ_CPF.equals(SAIDA.CNPJ_CPF)) || (lookUpValue_tDBSCD_1.COD_CIDADE == null && SAIDA.COD_CIDADE!= null) || (lookUpValue_tDBSCD_1.COD_CIDADE != null && !lookUpValue_tDBSCD_1.COD_CIDADE.equals(SAIDA.COD_CIDADE)) || (lookUpValue_tDBSCD_1.DATA_CADASTRO == null && SAIDA.DATA_CADASTRO!= null) || (lookUpValue_tDBSCD_1.DATA_CADASTRO != null && !lookUpValue_tDBSCD_1.DATA_CADASTRO.equals(SAIDA.DATA_CADASTRO)) || (lookUpValue_tDBSCD_1.ENDERECO == null && SAIDA.ENDERECO!= null) || (lookUpValue_tDBSCD_1.ENDERECO != null && !lookUpValue_tDBSCD_1.ENDERECO.equals(SAIDA.ENDERECO)) || (lookUpValue_tDBSCD_1.FANTASIA == null && SAIDA.FANTASIA!= null) || (lookUpValue_tDBSCD_1.FANTASIA != null && !lookUpValue_tDBSCD_1.FANTASIA.equals(SAIDA.FANTASIA)) || (lookUpValue_tDBSCD_1.NRO == null && SAIDA.NRO!= null) || (lookUpValue_tDBSCD_1.NRO != null && !lookUpValue_tDBSCD_1.NRO.equals(SAIDA.NRO)) || (lookUpValue_tDBSCD_1.RAZAO_CLIENTE == null && SAIDA.RAZAO_CLIENTE!= null) || (lookUpValue_tDBSCD_1.RAZAO_CLIENTE != null && !lookUpValue_tDBSCD_1.RAZAO_CLIENTE.equals(SAIDA.RAZAO_CLIENTE)) || (lookUpValue_tDBSCD_1.SITUACAO == null && SAIDA.SITUACAO!= null) || (lookUpValue_tDBSCD_1.SITUACAO != null && !lookUpValue_tDBSCD_1.SITUACAO.equals(SAIDA.SITUACAO)) || (lookUpValue_tDBSCD_1.TIPO_CLIENTE == null && SAIDA.TIPO_CLIENTE!= null) || (lookUpValue_tDBSCD_1.TIPO_CLIENTE != null && !lookUpValue_tDBSCD_1.TIPO_CLIENTE.equals(SAIDA.TIPO_CLIENTE))) {
                    if(SAIDA.BAIRRO == null) {
updateForType1_tDBSCD_1.setNull(1, java.sql.Types.VARCHAR);
} else {
updateForType1_tDBSCD_1.setString(1, SAIDA.BAIRRO);
}

                    if(SAIDA.CEP == null) {
updateForType1_tDBSCD_1.setNull(2, java.sql.Types.VARCHAR);
} else {
updateForType1_tDBSCD_1.setString(2, SAIDA.CEP);
}

                    if(SAIDA.CNPJ_CPF == null) {
updateForType1_tDBSCD_1.setNull(3, java.sql.Types.VARCHAR);
} else {
updateForType1_tDBSCD_1.setString(3, SAIDA.CNPJ_CPF);
}

                    if(SAIDA.COD_CIDADE == null) {
updateForType1_tDBSCD_1.setNull(4, java.sql.Types.VARCHAR);
} else {
updateForType1_tDBSCD_1.setString(4, SAIDA.COD_CIDADE);
}

                    if(SAIDA.DATA_CADASTRO == null) {
updateForType1_tDBSCD_1.setNull(5, java.sql.Types.DATE);
} else {
if(SAIDA.DATA_CADASTRO != null) {
updateForType1_tDBSCD_1.setTimestamp(5, new java.sql.Timestamp(SAIDA.DATA_CADASTRO.getTime()));
} else {
updateForType1_tDBSCD_1.setNull(5, java.sql.Types.DATE);
}
}

                    if(SAIDA.ENDERECO == null) {
updateForType1_tDBSCD_1.setNull(6, java.sql.Types.VARCHAR);
} else {
updateForType1_tDBSCD_1.setString(6, SAIDA.ENDERECO);
}

                    if(SAIDA.FANTASIA == null) {
updateForType1_tDBSCD_1.setNull(7, java.sql.Types.VARCHAR);
} else {
updateForType1_tDBSCD_1.setString(7, SAIDA.FANTASIA);
}

                    if(SAIDA.NRO == null) {
updateForType1_tDBSCD_1.setNull(8, java.sql.Types.VARCHAR);
} else {
updateForType1_tDBSCD_1.setString(8, SAIDA.NRO);
}

                    if(SAIDA.RAZAO_CLIENTE == null) {
updateForType1_tDBSCD_1.setNull(9, java.sql.Types.VARCHAR);
} else {
updateForType1_tDBSCD_1.setString(9, SAIDA.RAZAO_CLIENTE);
}

                    if(SAIDA.SITUACAO == null) {
updateForType1_tDBSCD_1.setNull(10, java.sql.Types.VARCHAR);
} else {
updateForType1_tDBSCD_1.setString(10, SAIDA.SITUACAO);
}

                    if(SAIDA.TIPO_CLIENTE == null) {
updateForType1_tDBSCD_1.setNull(11, java.sql.Types.VARCHAR);
} else {
updateForType1_tDBSCD_1.setString(11, SAIDA.TIPO_CLIENTE);
}

                    updateForType1_tDBSCD_1.setInt(12, SAIDA.ID_CLIENTE);

                    updateForType1_tDBSCD_1.setInt(13, SAIDA.COD_EMPRESA);

                nb_line_update_tDBSCD_1 += updateForType1_tDBSCD_1.executeUpdate();
            }
    }
    
	} catch (java.lang.Exception e) {//catch
  		
                System.err.print(e.getMessage());
	}//end catch
	
                lookUpValue_tDBSCD_1.BAIRRO = SAIDA.BAIRRO;
                lookUpValue_tDBSCD_1.CEP = SAIDA.CEP;
                lookUpValue_tDBSCD_1.CNPJ_CPF = SAIDA.CNPJ_CPF;
                lookUpValue_tDBSCD_1.COD_CIDADE = SAIDA.COD_CIDADE;
                lookUpValue_tDBSCD_1.DATA_CADASTRO = SAIDA.DATA_CADASTRO;
                lookUpValue_tDBSCD_1.ENDERECO = SAIDA.ENDERECO;
                lookUpValue_tDBSCD_1.FANTASIA = SAIDA.FANTASIA;
                lookUpValue_tDBSCD_1.NRO = SAIDA.NRO;
                lookUpValue_tDBSCD_1.RAZAO_CLIENTE = SAIDA.RAZAO_CLIENTE;
                lookUpValue_tDBSCD_1.SITUACAO = SAIDA.SITUACAO;
                lookUpValue_tDBSCD_1.TIPO_CLIENTE = SAIDA.TIPO_CLIENTE;
        cache_tDBSCD_1.put(lookUpKey_tDBSCD_1, lookUpValue_tDBSCD_1);


 


	tos_count_tDBSCD_1++;

/**
 * [tDBSCD_1 main ] stop
 */
	
	/**
	 * [tDBSCD_1 process_data_begin ] start
	 */

	

	
	
	currentComponent="tDBSCD_1";

	

 



/**
 * [tDBSCD_1 process_data_begin ] stop
 */
	
	/**
	 * [tDBSCD_1 process_data_end ] start
	 */

	

	
	
	currentComponent="tDBSCD_1";

	

 



/**
 * [tDBSCD_1 process_data_end ] stop
 */

} // End of branch "SAIDA"




	
	/**
	 * [tMap_1 process_data_end ] start
	 */

	

	
	
	currentComponent="tMap_1";

	

 



/**
 * [tMap_1 process_data_end ] stop
 */



	
	/**
	 * [tDBInput_1 process_data_end ] start
	 */

	

	
	
	currentComponent="tDBInput_1";

	

 



/**
 * [tDBInput_1 process_data_end ] stop
 */
	
	/**
	 * [tDBInput_1 end ] start
	 */

	

	
	
	currentComponent="tDBInput_1";

	

	}
}finally{
	if (rs_tDBInput_1 != null) {
		rs_tDBInput_1.close();
	}
	if (stmt_tDBInput_1 != null) {
		stmt_tDBInput_1.close();
	}
		if(conn_tDBInput_1 != null && !conn_tDBInput_1.isClosed()) {
			
			conn_tDBInput_1.close();
			
			if("com.mysql.cj.jdbc.Driver".equals((String)globalMap.get("driverClass_"))
			    && routines.system.BundleUtils.inOSGi()) {
			        Class.forName("com.mysql.cj.jdbc.AbandonedConnectionCleanupThread").
			            getMethod("checkedShutdown").invoke(null, (Object[]) null);
			}
			
		}
}
globalMap.put("tDBInput_1_NB_LINE",nb_line_tDBInput_1);

 

ok_Hash.put("tDBInput_1", true);
end_Hash.put("tDBInput_1", System.currentTimeMillis());




/**
 * [tDBInput_1 end ] stop
 */

	
	/**
	 * [tMap_1 end ] start
	 */

	

	
	
	currentComponent="tMap_1";

	


// ###############################
// # Lookup hashes releasing
// ###############################      





				if(execStat){
			  		runStat.updateStat(resourceMap,iterateId,2,0,"row1");
			  	}
			  	
 

ok_Hash.put("tMap_1", true);
end_Hash.put("tMap_1", System.currentTimeMillis());




/**
 * [tMap_1 end ] stop
 */

	
	/**
	 * [tDBSCD_1 end ] start
	 */

	

	
	
	currentComponent="tDBSCD_1";

	

    insertionStatement_tDBSCD_1.close();
        updateForType1_tDBSCD_1.close();
    
    if(conn_tDBSCD_1 != null && !conn_tDBSCD_1.isClosed()) {
        conn_tDBSCD_1.close();
    }    
    
    globalMap.put("tDBSCD_1_NB_LINE_UPDATED", nb_line_update_tDBSCD_1);
    globalMap.put("tDBSCD_1_NB_LINE_INSERTED", nb_line_inserted_tDBSCD_1);
    globalMap.put("tDBSCD_1_NB_LINE_REJECTED",nb_line_rejected_tDBSCD_1);

				if(execStat){
			  		runStat.updateStat(resourceMap,iterateId,2,0,"SAIDA");
			  	}
			  	
 

ok_Hash.put("tDBSCD_1", true);
end_Hash.put("tDBSCD_1", System.currentTimeMillis());




/**
 * [tDBSCD_1 end ] stop
 */






				}//end the resume

				



	
			}catch(java.lang.Exception e){	
				
				TalendException te = new TalendException(e, currentComponent, globalMap);
				
				throw te;
			}catch(java.lang.Error error){	
				
					runStat.stopThreadStat();
				
				throw error;
			}finally{
				
				try{
					
	
	/**
	 * [tDBInput_1 finally ] start
	 */

	

	
	
	currentComponent="tDBInput_1";

	

 



/**
 * [tDBInput_1 finally ] stop
 */

	
	/**
	 * [tMap_1 finally ] start
	 */

	

	
	
	currentComponent="tMap_1";

	

 



/**
 * [tMap_1 finally ] stop
 */

	
	/**
	 * [tDBSCD_1 finally ] start
	 */

	

	
	
	currentComponent="tDBSCD_1";

	

 



/**
 * [tDBSCD_1 finally ] stop
 */






				}catch(java.lang.Exception e){	
					//ignore
				}catch(java.lang.Error error){
					//ignore
				}
				resourceMap = null;
			}
		

		globalMap.put("tDBInput_1_SUBPROCESS_STATE", 1);
	}
	
    public String resuming_logs_dir_path = null;
    public String resuming_checkpoint_path = null;
    public String parent_part_launcher = null;
    private String resumeEntryMethodName = null;
    private boolean globalResumeTicket = false;

    public boolean watch = false;
    // portStats is null, it means don't execute the statistics
    public Integer portStats = null;
    public int portTraces = 4334;
    public String clientHost;
    public String defaultClientHost = "localhost";
    public String contextStr = "Default";
    public boolean isDefaultContext = true;
    public String pid = "0";
    public String rootPid = null;
    public String fatherPid = null;
    public String fatherNode = null;
    public long startTime = 0;
    public boolean isChildJob = false;
    public String log4jLevel = "";
    
    private boolean enableLogStash;

    private boolean execStat = true;

    private ThreadLocal<java.util.Map<String, String>> threadLocal = new ThreadLocal<java.util.Map<String, String>>() {
        protected java.util.Map<String, String> initialValue() {
            java.util.Map<String,String> threadRunResultMap = new java.util.HashMap<String, String>();
            threadRunResultMap.put("errorCode", null);
            threadRunResultMap.put("status", "");
            return threadRunResultMap;
        };
    };


    private PropertiesWithType context_param = new PropertiesWithType();
    public java.util.Map<String, Object> parentContextMap = new java.util.HashMap<String, Object>();

    public String status= "";
    

    public static void main(String[] args){
        final CARGA_DIM_CLIENTES CARGA_DIM_CLIENTESClass = new CARGA_DIM_CLIENTES();

        int exitCode = CARGA_DIM_CLIENTESClass.runJobInTOS(args);

        System.exit(exitCode);
    }


    public String[][] runJob(String[] args) {

        int exitCode = runJobInTOS(args);
        String[][] bufferValue = new String[][] { { Integer.toString(exitCode) } };

        return bufferValue;
    }

    public boolean hastBufferOutputComponent() {
		boolean hastBufferOutput = false;
    	
        return hastBufferOutput;
    }

    public int runJobInTOS(String[] args) {
	   	// reset status
	   	status = "";
	   	
        String lastStr = "";
        for (String arg : args) {
            if (arg.equalsIgnoreCase("--context_param")) {
                lastStr = arg;
            } else if (lastStr.equals("")) {
                evalParam(arg);
            } else {
                evalParam(lastStr + " " + arg);
                lastStr = "";
            }
        }
        enableLogStash = "true".equalsIgnoreCase(System.getProperty("monitoring"));

    	
    	

        if(clientHost == null) {
            clientHost = defaultClientHost;
        }

        if(pid == null || "0".equals(pid)) {
            pid = TalendString.getAsciiRandomString(6);
        }

        if (rootPid==null) {
            rootPid = pid;
        }
        if (fatherPid==null) {
            fatherPid = pid;
        }else{
            isChildJob = true;
        }

        if (portStats != null) {
            // portStats = -1; //for testing
            if (portStats < 0 || portStats > 65535) {
                // issue:10869, the portStats is invalid, so this client socket can't open
                System.err.println("The statistics socket port " + portStats + " is invalid.");
                execStat = false;
            }
        } else {
            execStat = false;
        }

        try {
            //call job/subjob with an existing context, like: --context=production. if without this parameter, there will use the default context instead.
            java.io.InputStream inContext = CARGA_DIM_CLIENTES.class.getClassLoader().getResourceAsStream("bi_forest/carga_dim_clientes_0_1/contexts/" + contextStr + ".properties");
            if (inContext == null) {
                inContext = CARGA_DIM_CLIENTES.class.getClassLoader().getResourceAsStream("config/contexts/" + contextStr + ".properties");
            }
            if (inContext != null) {
                //defaultProps is in order to keep the original context value
                if(context != null && context.isEmpty()) {
	                defaultProps.load(inContext);
	                context = new ContextProperties(defaultProps);
                }
                
                inContext.close();
            } else if (!isDefaultContext) {
                //print info and job continue to run, for case: context_param is not empty.
                System.err.println("Could not find the context " + contextStr);
            }

            if(!context_param.isEmpty()) {
                context.putAll(context_param);
				//set types for params from parentJobs
				for (Object key: context_param.keySet()){
					String context_key = key.toString();
					String context_type = context_param.getContextType(context_key);
					context.setContextType(context_key, context_type);

				}
            }
            class ContextProcessing {
                private void processContext_0() {
                } 
                public void processAllContext() {
                        processContext_0();
                }
            }

            new ContextProcessing().processAllContext();
        } catch (java.io.IOException ie) {
            System.err.println("Could not load context "+contextStr);
            ie.printStackTrace();
        }

        // get context value from parent directly
        if (parentContextMap != null && !parentContextMap.isEmpty()) {
        }

        //Resume: init the resumeUtil
        resumeEntryMethodName = ResumeUtil.getResumeEntryMethodName(resuming_checkpoint_path);
        resumeUtil = new ResumeUtil(resuming_logs_dir_path, isChildJob, rootPid);
        resumeUtil.initCommonInfo(pid, rootPid, fatherPid, projectName, jobName, contextStr, jobVersion);

		List<String> parametersToEncrypt = new java.util.ArrayList<String>();
        //Resume: jobStart
        resumeUtil.addLog("JOB_STARTED", "JOB:" + jobName, parent_part_launcher, Thread.currentThread().getId() + "", "","","","",resumeUtil.convertToJsonText(context,parametersToEncrypt));

if(execStat) {
    try {
        runStat.openSocket(!isChildJob);
        runStat.setAllPID(rootPid, fatherPid, pid, jobName);
        runStat.startThreadStat(clientHost, portStats);
        runStat.updateStatOnJob(RunStat.JOBSTART, fatherNode);
    } catch (java.io.IOException ioException) {
        ioException.printStackTrace();
    }
}



	
	    java.util.concurrent.ConcurrentHashMap<Object, Object> concurrentHashMap = new java.util.concurrent.ConcurrentHashMap<Object, Object>();
	    globalMap.put("concurrentHashMap", concurrentHashMap);
	

    long startUsedMemory = Runtime.getRuntime().totalMemory() - Runtime.getRuntime().freeMemory();
    long endUsedMemory = 0;
    long end = 0;

    startTime = System.currentTimeMillis();




this.globalResumeTicket = true;//to run tPreJob




this.globalResumeTicket = false;//to run others jobs

try {
errorCode = null;tDBInput_1Process(globalMap);
if(!"failure".equals(status)) { status = "end"; }
}catch (TalendException e_tDBInput_1) {
globalMap.put("tDBInput_1_SUBPROCESS_STATE", -1);

e_tDBInput_1.printStackTrace();

}

this.globalResumeTicket = true;//to run tPostJob




        end = System.currentTimeMillis();

        if (watch) {
            System.out.println((end-startTime)+" milliseconds");
        }

        endUsedMemory = Runtime.getRuntime().totalMemory() - Runtime.getRuntime().freeMemory();
        if (false) {
            System.out.println((endUsedMemory - startUsedMemory) + " bytes memory increase when running : CARGA_DIM_CLIENTES");
        }



if (execStat) {
    runStat.updateStatOnJob(RunStat.JOBEND, fatherNode);
    runStat.stopThreadStat();
}
    int returnCode = 0;
    if(errorCode == null) {
         returnCode = status != null && status.equals("failure") ? 1 : 0;
    } else {
         returnCode = errorCode.intValue();
    }
    resumeUtil.addLog("JOB_ENDED", "JOB:" + jobName, parent_part_launcher, Thread.currentThread().getId() + "", "","" + returnCode,"","","");

    return returnCode;

  }

    // only for OSGi env
    public void destroy() {


    }














    private java.util.Map<String, Object> getSharedConnections4REST() {
        java.util.Map<String, Object> connections = new java.util.HashMap<String, Object>();







        return connections;
    }

    private void evalParam(String arg) {
        if (arg.startsWith("--resuming_logs_dir_path")) {
            resuming_logs_dir_path = arg.substring(25);
        } else if (arg.startsWith("--resuming_checkpoint_path")) {
            resuming_checkpoint_path = arg.substring(27);
        } else if (arg.startsWith("--parent_part_launcher")) {
            parent_part_launcher = arg.substring(23);
        } else if (arg.startsWith("--watch")) {
            watch = true;
        } else if (arg.startsWith("--stat_port=")) {
            String portStatsStr = arg.substring(12);
            if (portStatsStr != null && !portStatsStr.equals("null")) {
                portStats = Integer.parseInt(portStatsStr);
            }
        } else if (arg.startsWith("--trace_port=")) {
            portTraces = Integer.parseInt(arg.substring(13));
        } else if (arg.startsWith("--client_host=")) {
            clientHost = arg.substring(14);
        } else if (arg.startsWith("--context=")) {
            contextStr = arg.substring(10);
            isDefaultContext = false;
        } else if (arg.startsWith("--father_pid=")) {
            fatherPid = arg.substring(13);
        } else if (arg.startsWith("--root_pid=")) {
            rootPid = arg.substring(11);
        } else if (arg.startsWith("--father_node=")) {
            fatherNode = arg.substring(14);
        } else if (arg.startsWith("--pid=")) {
            pid = arg.substring(6);
        } else if (arg.startsWith("--context_type")) {
            String keyValue = arg.substring(15);
			int index = -1;
            if (keyValue != null && (index = keyValue.indexOf('=')) > -1) {
                if (fatherPid==null) {
                    context_param.setContextType(keyValue.substring(0, index), replaceEscapeChars(keyValue.substring(index + 1)));
                } else { // the subjob won't escape the especial chars
                    context_param.setContextType(keyValue.substring(0, index), keyValue.substring(index + 1) );
                }

            }

		} else if (arg.startsWith("--context_param")) {
            String keyValue = arg.substring(16);
            int index = -1;
            if (keyValue != null && (index = keyValue.indexOf('=')) > -1) {
                if (fatherPid==null) {
                    context_param.put(keyValue.substring(0, index), replaceEscapeChars(keyValue.substring(index + 1)));
                } else { // the subjob won't escape the especial chars
                    context_param.put(keyValue.substring(0, index), keyValue.substring(index + 1) );
                }
            }
        } else if (arg.startsWith("--log4jLevel=")) {
            log4jLevel = arg.substring(13);
		} else if (arg.startsWith("--monitoring") && arg.contains("=")) {//for trunjob call
		    final int equal = arg.indexOf('=');
			final String key = arg.substring("--".length(), equal);
			System.setProperty(key, arg.substring(equal + 1));
		}
    }
    
    private static final String NULL_VALUE_EXPRESSION_IN_COMMAND_STRING_FOR_CHILD_JOB_ONLY = "<TALEND_NULL>";

    private final String[][] escapeChars = {
        {"\\\\","\\"},{"\\n","\n"},{"\\'","\'"},{"\\r","\r"},
        {"\\f","\f"},{"\\b","\b"},{"\\t","\t"}
        };
    private String replaceEscapeChars (String keyValue) {

		if (keyValue == null || ("").equals(keyValue.trim())) {
			return keyValue;
		}

		StringBuilder result = new StringBuilder();
		int currIndex = 0;
		while (currIndex < keyValue.length()) {
			int index = -1;
			// judege if the left string includes escape chars
			for (String[] strArray : escapeChars) {
				index = keyValue.indexOf(strArray[0],currIndex);
				if (index>=0) {

					result.append(keyValue.substring(currIndex, index + strArray[0].length()).replace(strArray[0], strArray[1]));
					currIndex = index + strArray[0].length();
					break;
				}
			}
			// if the left string doesn't include escape chars, append the left into the result
			if (index < 0) {
				result.append(keyValue.substring(currIndex));
				currIndex = currIndex + keyValue.length();
			}
		}

		return result.toString();
    }

    public Integer getErrorCode() {
        return errorCode;
    }


    public String getStatus() {
        return status;
    }

    ResumeUtil resumeUtil = null;
}
/************************************************************************************************
 *     74461 characters generated by Talend Open Studio for Data Integration 
 *     on the 19 de Maio de 2024 22h4min4s BRT
 ************************************************************************************************/